[workspace]
members = ["pocketbase-derive"]

[package]
name        = "pocketbase-sdk"
version     = "0.0.4"
edition     = "2021"
authors     = ["Sreedev Kodichath <sreedev@icloud.com>"]
license     = "MIT"
description = "WebAsm Compatible Pocketbase SDK"
readme      = "README.md"
homepage    = "https://github.com/sreedevk/pocketbase-sdk-rust"
categories  = ["development-tools"]
keywords    = [
  "pocketbase",
  "pocketbase-sdk",
  "rust-pocketbase",
  "pocketbase-rs"
]


[dependencies]
log                   = "0.4.17"
reqwest               = { version = "0.11", features = ["json", "blocking"] }
serde                 = { version = "1.0.145", features = ["derive"] }
serde_json            = "1.0.85"
url                   = "2.3.1"
pocketbase_derive     = { version = "0.0.1", path = "./pocketbase-derive" }

[dev-dependencies]
httpmock = "0.6"
pocketbase_derive     = { version = "0.0.1", path = "./pocketbase-derive" }
tokio                 = { version = "1", features = ["full"] }
