name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build x86
      run: cargo build --verbose
    - name: Build Wasm32
      run: cargo build --verbase --target wasm32-unknown-unknown
    - name: Run tests
      run: cargo test --verbose
